export const locationData = {
  // Values must align with the local_taxes table (case-insensitive match on backend).
  Indiana: [
    'union',
    'grant',
    'carroll',
    'howard',
    'greene',
    'shelby',
    'marion',
    'hamilton',
    'allen',
    'st. joseph',
    'vanderburgh',
    'lake',
    'monroe',
    'cass',
    'other',
  ],
  Maryland: [
    'baltimore city',
    'montgomery',
    'prince george',
    'anne arundel',
    'howard',
    'frederick',
    'talbot',
    'worcester',
    'other',
  ],
  Michigan: [
    'detroit',
    'other',
  ],
  'New York': [
    'yonkers',
    'manhattan',
    'brooklyn',
    'queens',
    'bronx',
    'staten island',
    'other',
  ],
};
