export const mockResults = [
    {
        id: 'citi-bank-cd-1',
        provider: 'Citibank',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.30,
        afterTaxYield: 2.87,
        minDeposit: 1000,
        isTopPick: true,
        taxBreakdown: {
            federalBracket: '-$11,500',
            stateTax: '-$664.00',
            localOswego: '$0.00%'
        },
        netReturn: '$1,861.00',
        whyThisFits: 'This Citibank CD matches your profile because it offers a secure, FDIC-insured account with a predictable return. With a 4.30% APY, your after-tax yield remains a competitive 2.87%, providing a stable income with clear expectations on tax implications. It offers the reliability of a top-tier bank with simple structure for conservative investors.',
        matchPercentage: 92
    },
    {
        id: 'citi-brokerage-cd-1',
        provider: 'Citibank',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 4.30,
        afterTaxYield: 2.87,
        minDeposit: 1000,
        isTopPick: true,
        taxBreakdown: {
            federalBracket: '-$11,500',
            stateTax: '-$664.00',
            localOswego: '$0.00%'
        },
        netReturn: '$1,861.00',
        whyThisFits: 'This Citibank CD matches your profile because it offers a secure, FDIC-insured account with a predictable return. With a 4.30% APY, your after-tax yield remains a competitive 2.87%, providing a stable income with clear expectations on tax implications. It offers the reliability of a top-tier bank with simple structure for conservative investors.',
        matchPercentage: 92
    },
    {
        id: 'treasury-1',
        provider: 'US Treasury',
        institutionType: 'Backed by U.S. Government',
        productType: 'Treasuries',
        nominalRate: 4.30,
        afterTaxYield: 2.87,
        minDeposit: 1000,
        isTopPick: true,
        taxBreakdown: {
            federalBracket: '-$11,500',
            stateTax: '$0.00',
            localOswego: '$0.00%'
        },
        netReturn: '$1,861.00',
        whyThisFits: 'US Treasuries are exempt from state and local taxes, making their lower nominal rate more competitive on an after-tax basis. Backed by the full faith and credit of the US Government.',
        matchPercentage: 92
    },
    {
        id: 'bofa-1',
        provider: 'Bank of America',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.25,
        afterTaxYield: 2.83,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$11,200', stateTax: '-$650.00', localOswego: '$0.00%' },
        netReturn: '$1,820.00',
        whyThisFits: 'Offers widespread branch access and solid yields for conservative investors.',
        matchPercentage: 88
    },
    {
        id: 'morgan-1',
        provider: 'Morgan Stanley',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.20,
        afterTaxYield: 2.82,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$11,000', stateTax: '-$640.00', localOswego: '$0.00%' },
        netReturn: '$1,800.00',
        whyThisFits: 'Solid institutional backing with competitive yields.',
        matchPercentage: 87
    },
    {
        id: 'barclays-1',
        provider: 'Barclays Bank',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 4.10,
        afterTaxYield: 2.81,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,800', stateTax: '-$620.00', localOswego: '$0.00%' },
        netReturn: '$1,780.00',
        whyThisFits: 'Great rate from an international banking leader, accessible via brokerage.',
        matchPercentage: 85
    },
    {
        id: 'mizuho-1',
        provider: 'Mizuho Bank',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.05,
        afterTaxYield: 2.81,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,600', stateTax: '-$600.00', localOswego: '$0.00%' },
        netReturn: '$1,750.00',
        whyThisFits: 'Competitive rate from a strong global financial institution.',
        matchPercentage: 84
    },
    {
        id: 'goldman-1',
        provider: 'Goldman Sachs',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 4.02,
        afterTaxYield: 2.80,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,500', stateTax: '-$590.00', localOswego: '$0.00%' },
        netReturn: '$1,740.00',
        whyThisFits: 'Premium brand with stable returns for brokerage accounts.',
        matchPercentage: 82
    },
    {
        id: 'chase-1',
        provider: 'JP Morgan Chase',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.00,
        afterTaxYield: 2.78,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,400', stateTax: '-$580.00', localOswego: '$0.00%' },
        netReturn: '$1,720.00',
        whyThisFits: 'The largest US bank offering security and convenience.',
        matchPercentage: 80
    },
    {
        id: 'capital-1',
        provider: 'Capital One',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.00,
        afterTaxYield: 2.76,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,400', stateTax: '-$580.00', localOswego: '$0.00%' },
        netReturn: '$1,700.00',
        whyThisFits: 'Known for no-fee banking and easy online management.',
        matchPercentage: 78
    },
    {
        id: 'discover-1',
        provider: 'Discover Bank',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 3.95,
        afterTaxYield: 2.75,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,200', stateTax: '-$560.00', localOswego: '$0.00%' },
        netReturn: '$1,680.00',
        whyThisFits: 'Reliable customer service and decent yields on the brokerage platform.',
        matchPercentage: 75
    },
    {
        id: 'morgan-2',
        provider: 'Morgan Stanley',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.20,
        afterTaxYield: 2.82,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$11,000', stateTax: '-$640.00', localOswego: '$0.00%' },
        netReturn: '$1,800.00',
        whyThisFits: 'Solid institutional backing with competitive yields.',
        matchPercentage: 87
    },
    {
        id: 'barclays-2',
        provider: 'Barclays Bank',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 4.10,
        afterTaxYield: 2.81,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,800', stateTax: '-$620.00', localOswego: '$0.00%' },
        netReturn: '$1,780.00',
        whyThisFits: 'Great rate from an international banking leader, accessible via brokerage.',
        matchPercentage: 85
    },
    {
        id: 'mizuho-2',
        provider: 'Mizuho Bank',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.05,
        afterTaxYield: 2.81,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,600', stateTax: '-$600.00', localOswego: '$0.00%' },
        netReturn: '$1,750.00',
        whyThisFits: 'Competitive rate from a strong global financial institution.',
        matchPercentage: 84
    },
    {
        id: 'goldman-2',
        provider: 'Goldman Sachs',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 4.02,
        afterTaxYield: 2.80,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,500', stateTax: '-$590.00', localOswego: '$0.00%' },
        netReturn: '$1,740.00',
        whyThisFits: 'Premium brand with stable returns for brokerage accounts.',
        matchPercentage: 82
    },
    {
        id: 'chase-2',
        provider: 'JP Morgan Chase',
        institutionType: 'Member of FDIC',
        productType: 'Bank CDs',
        nominalRate: 4.00,
        afterTaxYield: 2.78,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,400', stateTax: '-$580.00', localOswego: '$0.00%' },
        netReturn: '$1,720.00',
        whyThisFits: 'The largest US bank offering security and convenience.',
        matchPercentage: 80
    },
    {
        id: 'discover-2',
        provider: 'Discover Bank',
        institutionType: 'Member of FDIC, Issued through Fidelity',
        productType: 'Brokerage CDs',
        nominalRate: 3.95,
        afterTaxYield: 2.75,
        minDeposit: 1000,
        isTopPick: false,
        taxBreakdown: { federalBracket: '-$10,200', stateTax: '-$560.00', localOswego: '$0.00%' },
        netReturn: '$1,680.00',
        whyThisFits: 'Reliable customer service and decent yields on the brokerage platform.',
        matchPercentage: 75
    }
];
